apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storybook-ingress-qa
  annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: storybook-qa
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storybook-svc-qa
            port:
              name: storybook-qa



